// Editorial grouping of the tool catalog for the dashboard Tools reference. Tool
// NAMES only — each tool's description + read-only/write flag come from
// tools-catalog.json (generated from the manifest). tools-catalog.test.ts asserts
// every catalog tool is categorized exactly once, so this can't silently drift.

export interface ToolCategory {
  category: string;
  icon: string;
  blurb: string;
  tools: string[];
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    category: "Company & Setup",
    icon: "🏢",
    blurb: "Connect companies, switch between them, and view configuration.",
    tools: [
      "qb_company_info",
      "qb_list_companies",
      "qb_switch_company",
      "qb_refresh_connection",
      "qb_server_info",
      "qb_tax_data_info",
      "qb_list_tax_codes",
      "qb_list_tax_rates",
    ],
  },
  {
    category: "Accounts, Vendors & Customers",
    icon: "👥",
    blurb: "Chart of accounts, items, classes, and vendor/customer records.",
    tools: [
      "qb_list_accounts",
      "qb_create_account",
      "qb_create_sub_account",
      "qb_inactivate_account",
      "qb_list_items",
      "qb_list_classes",
      "qb_list_departments",
      "qb_list_vendors",
      "qb_create_vendor",
      "qb_update_vendor",
      "qb_bulk_update_vendor",
      "qb_bulk_update_vendors_multi",
      "qb_vendor_summary",
      "qb_vendor_expenses",
      "qb_vendor_balance_detail",
      "qb_unknown_vendor_report",
      "qb_list_customers",
      "qb_create_customer",
      "qb_update_customer",
      "qb_customer_balance_detail",
    ],
  },
  {
    category: "Transactions",
    icon: "📊",
    blurb: "View, search, create, and adjust every transaction type.",
    tools: [
      "qb_list_transactions",
      "qb_transaction_list",
      "qb_transaction_detail",
      "qb_account_transactions",
      "qb_account_balance",
      "qb_search_transactions",
      "qb_list_deposits",
      "qb_create_deposit",
      "qb_list_transfers",
      "qb_create_transfer",
      "qb_list_journal_entries",
      "qb_list_journal_entries_by_memo",
      "qb_create_journal_entry",
      "qb_batch_create_journal_entries",
      "qb_delete_journal_entry",
      "qb_create_expense",
      "qb_batch_create_expenses",
      "qb_create_bill",
      "qb_batch_create_bills",
      "qb_list_bills",
      "qb_list_bill_payments",
      "qb_record_bill_payment",
      "qb_list_recurring_transactions",
      "qb_update_transaction",
      "qb_delete_transaction",
      "qb_void_transaction",
      "qb_reclassify_transaction",
      "qb_list_attachments",
      "qb_upload_receipt",
      "qb_missing_receipts",
      "qb_list_purchase_orders",
      "qb_change_audit_trail",
    ],
  },
  {
    category: "Sales, Invoicing & Payments",
    icon: "🧾",
    blurb: "Invoices, estimates, credit memos, payments, and A/R & A/P aging.",
    tools: [
      "qb_list_invoices",
      "qb_create_invoice",
      "qb_send_invoice",
      "qb_list_estimates",
      "qb_create_estimate",
      "qb_convert_estimate_to_invoice",
      "qb_list_credit_memos",
      "qb_create_credit_memo",
      "qb_list_sales_receipts",
      "qb_list_payments",
      "qb_record_invoice_payment",
      "qb_send_payment_reminders",
      "qb_list_vendor_credits",
      "qb_create_vendor_credit",
      "qb_match_invoices_to_transactions",
      "qb_reconcile_invoices",
      "qb_ar_aging",
      "qb_ap_aging",
    ],
  },
  {
    category: "Reports & Analysis",
    icon: "📈",
    blurb: "Financial statements, sales breakdowns, and cash-flow analytics.",
    tools: [
      "qb_profit_loss",
      "qb_profit_loss_detail",
      "qb_profit_loss_by_class",
      "qb_profit_loss_by_department",
      "qb_balance_sheet",
      "qb_cash_flow",
      "qb_cash_flow_forecast",
      "qb_trial_balance",
      "qb_general_ledger",
      "qb_comparative_statements",
      "qb_compare_periods",
      "qb_budget_vs_actual",
      "qb_income_summary",
      "qb_expense_summary",
      "qb_inventory_valuation",
      "qb_profit_margin_analysis",
      "qb_monthly_burn_rate",
      "qb_runway_calculator",
      "qb_sales_by_customer",
      "qb_sales_by_product",
      "qb_sales_by_class",
      "qb_sales_by_department",
      "qb_sales_tax_summary",
    ],
  },
  {
    category: "Bookkeeping & Reconciliation",
    icon: "🧹",
    blurb:
      "Categorization, dedupe, anomaly checks, reconciliation, and closes.",
    tools: [
      "qb_auto_categorize_suggestions",
      "qb_apply_categorization_rules",
      "qb_categorization_rules",
      "qb_uncategorized_transactions",
      "qb_find_duplicates",
      "qb_anomaly_detection",
      "qb_books_health_audit",
      "qb_books_hygiene",
      "qb_bank_reconciliation",
      "qb_reconciliation_status",
      "qb_stripe_reconcile",
      "qb_month_end_close",
      "qb_fiscal_year_close_checklist",
      "qb_owner_draws",
      "qb_allocation_profile",
    ],
  },
  {
    category: "Tax — United States",
    icon: "🇺🇸",
    blurb: "Schedule C, 1120S/1065, quarterly estimates, 1099s, depreciation.",
    tools: [
      "qb_schedule_c",
      "qb_schedule_c_detailed",
      "qb_form_1120s_summary",
      "qb_form_1065_summary",
      "qb_tax_summary",
      "qb_estimate_quarterly_tax",
      "qb_deduction_finder",
      "qb_1099_contractor_report",
      "qb_1099_misc_report",
      "qb_sales_tax_nexus",
      "qb_home_office_calculator",
      "qb_startup_cost_analysis",
      "qb_vehicle_depreciation_calculator",
      "qb_depreciation_schedule",
      "qb_record_depreciation",
      "qb_tax_payments_made",
      "qb_payroll_checklist",
    ],
  },
  {
    category: "Tax — Canada",
    icon: "🇨🇦",
    blurb: "T2125, GST/HST returns, CRA instalments, CCA, T4A.",
    tools: [
      "qb_t2125_summary",
      "qb_gst_hst_return",
      "qb_estimate_instalments",
      "qb_cca_schedule",
      "qb_t4a_contractor_report",
    ],
  },
];
